package com.example.backend.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Narrow acknowledgement returned by {@code POST /api/cases}.
 *
 * Kept intentionally thin (just {@code caseId} + {@code status}) so the
 * consultor UI doesn't need to parse the whole case graph right after
 * creation; callers that want the full shape hit
 * {@code GET /api/case-files/{id}} afterwards.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class StartCaseResponseDTO {

    private String caseId;

    /** Always {@code "CREATED"} on the success path. */
    private String status;

    /** Human-readable case code generated by the engine (e.g. "CASE-AB12CD34"). */
    private String code;
}
